- block:
  - name: Add Docker GPG key
    become: yes
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: Add Docker APT repository
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      state: present

  - name: Update apt cache after adding Docker repo
    apt:
      update_cache: yes

  - name: Install Docker
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Enable and start Docker service
    systemd:
      name: docker
      enabled: yes
      state: started
  tags: [install]
